name: GolfBets
options:
  bundleIdPrefix: com.shawncheatham
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "16.2"
settings:
  base:
    SWIFT_VERSION: 5.0
packages: {}
targets:
  GolfBets:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shawncheatham.golfbets
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.sports
        ENABLE_PREVIEWS: YES
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Golf Bets
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations~iphone:
          - UIInterfaceOrientationPortrait
        UIApplicationSupportsIndirectInputEvents: true
        UIRequiresFullScreen: true
        UIStatusBarStyle: UIStatusBarStyleDefault
        UIViewControllerBasedStatusBarAppearance: true
        UIUserInterfaceStyle: Automatic
